# Generated by Django 5.1.6 on 2025-07-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalGasNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burner_replacement_quantity', models.FloatField(default=2, help_text='Quantity of burner replacements')),
                ('burner_replacement_unit_price', models.FloatField(default=1800.0, help_text='Unit price for burner replacement (€)')),
                ('gas_pipes_quantity', models.FloatField(default=1, help_text='Quantity of gas pipes')),
                ('gas_pipes_unit_price', models.FloatField(default=700.0, help_text='Unit price for gas pipes (€)')),
                ('gas_detection_systems_quantity', models.FloatField(default=7, help_text='Quantity of gas detection systems')),
                ('gas_detection_systems_unit_price', models.FloatField(default=200.0, help_text='Unit price for gas detection systems (€)')),
                ('boiler_cleaning_quantity', models.FloatField(default=1, help_text='Quantity of boiler cleaning services')),
                ('boiler_cleaning_unit_price', models.FloatField(default=364.0, help_text='Unit price for boiler cleaning (€)')),
                ('current_energy_cost_per_year', models.FloatField(blank=True, help_text='Current annual energy cost (€)', null=True)),
                ('natural_gas_cost_per_year', models.FloatField(blank=True, help_text='Annual natural gas cost (€)', null=True)),
                ('annual_energy_savings', models.FloatField(blank=True, help_text='Annual energy savings (€)', null=True)),
                ('lifespan_years', models.IntegerField(default=15, help_text='Project lifespan in years')),
                ('burner_replacement_subtotal', models.FloatField(default=0.0, help_text='Burner replacement subtotal (€)')),
                ('gas_pipes_subtotal', models.FloatField(default=0.0, help_text='Gas pipes subtotal (€)')),
                ('gas_detection_systems_subtotal', models.FloatField(default=0.0, help_text='Gas detection systems subtotal (€)')),
                ('boiler_cleaning_subtotal', models.FloatField(default=0.0, help_text='Boiler cleaning subtotal (€)')),
                ('total_investment_cost', models.FloatField(default=0.0, help_text='Total investment cost (€)')),
                ('annual_economic_benefit', models.FloatField(default=0.0, help_text='Annual economic benefit (€)')),
                ('payback_period', models.FloatField(default=0.0, help_text='Payback period (years)')),
                ('net_present_value', models.FloatField(default=0.0, help_text='Net Present Value (€)')),
                ('internal_rate_of_return', models.FloatField(default=0.0, help_text='Internal Rate of Return (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_gas_networks', to='building.building')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='natural_gas_networks', to='project.project')),
            ],
            options={
                'verbose_name': 'Natural Gas Network',
                'verbose_name_plural': 'Natural Gas Networks',
                'db_table': 'natural_gas_network',
                'ordering': ['-created_at'],
            },
        ),
    ]
