# Generated by Django 5.1.6 on 2025-08-01 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalGasNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalgasnetwork',
            name='natural_gas_price_per_kwh',
            field=models.FloatField(blank=True, help_text='Natural gas price per kWh (€/kWh)', null=True),
        ),
        migrations.AddField(
            model_name='naturalgasnetwork',
            name='new_system_efficiency',
            field=models.FloatField(default=0.9, help_text='Efficiency of new natural gas system (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
