# Generated by Django 5.1.6 on 2025-09-30 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('naturalGasNetwork', '0002_naturalgasnetwork_natural_gas_price_per_kwh_and_more'),
        ('project', '0003_project_is_submitted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naturalgasnetwork',
            unique_together={('building', 'project')},
        ),
    ]
