# Generated by Django 4.2.3 on 2025-11-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalGasNetwork', '0003_alter_naturalgasnetwork_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalgasnetwork',
            name='annual_operating_expenses',
            field=models.FloatField(default=0.0, help_text='Annual operating expenses (€)'),
        ),
        migrations.AddField(
            model_name='naturalgasnetwork',
            name='discount_rate',
            field=models.FloatField(default=5.0, help_text='Discount rate (%)'),
        ),
    ]
