# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalGasNetwork', '0009_naturalgasnetwork_discounted_payback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalgasnetwork',
            name='current_energy_cost_per_year',
            field=models.FloatField(blank=True, help_text='Annual heating oil energy cost (€)', null=True),
        ),
    ]
