# Generated by Django 5.1.6 on 2025-07-27 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulbReplacement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_bulb_type', models.CharField(default='Λαμπτήρας Πυρακτώσεως', help_text='Τύπος του παλαιού λαμπτήρα', max_length=255, verbose_name='Τύπος παλαιού φορτίου')),
                ('old_power_per_bulb', models.FloatField(help_text='Ισχύς του παλαιού λαμπτήρα σε Watts', verbose_name='Ισχύς παλαιού φορτίου (W)')),
                ('old_bulb_count', models.IntegerField(help_text='Αριθμός παλαιών λαμπτήρων', verbose_name='Πλήθος παλαιών λαμπτήρων')),
                ('old_operating_hours', models.FloatField(help_text='Ώρες λειτουργίας των παλαιών λαμπτήρων ανά έτος', verbose_name='Ώρες λειτουργίας παλαιών λαμπτήρων ανά έτος')),
                ('old_consumption_kwh', models.FloatField(blank=True, help_text='Ετήσια κατανάλωση παλαιών λαμπτήρων σε kWh', null=True, verbose_name='Κατανάλωση παλαιών λαμπτήρων (kWh)')),
                ('new_bulb_type', models.CharField(default='LED Λαμπτήρας', help_text='Τύπος του νέου λαμπτήρα', max_length=255, verbose_name='Τύπος νέου φορτίου')),
                ('new_power_per_bulb', models.FloatField(help_text='Ισχύς του νέου λαμπτήρα σε Watts', verbose_name='Ισχύς νέου φορτίου (W)')),
                ('new_bulb_count', models.IntegerField(help_text='Αριθμός νέων λαμπτήρων', verbose_name='Πλήθος νέων λαμπτήρων')),
                ('new_operating_hours', models.FloatField(help_text='Ώρες λειτουργίας των νέων λαμπτήρων ανά έτος', verbose_name='Ώρες λειτουργίας νέων λαμπτήρων ανά έτος')),
                ('new_consumption_kwh', models.FloatField(blank=True, help_text='Ετήσια κατανάλωση νέων λαμπτήρων σε kWh', null=True, verbose_name='Κατανάλωση νέων λαμπτήρων (kWh)')),
                ('cost_per_new_bulb', models.FloatField(blank=True, help_text='Κόστος αγοράς ενός νέου λαμπτήρα', null=True, verbose_name='Κόστος ανά νέο λαμπτήρα (€)')),
                ('installation_cost', models.FloatField(blank=True, default=0, help_text='Επιπρόσθετο κόστος για την εγκατάσταση', null=True, verbose_name='Κόστος εγκατάστασης (€)')),
                ('energy_cost_kwh', models.FloatField(blank=True, help_text='Κόστος ενεργειακής μονάδας', null=True, verbose_name='Κόστος ενέργειας (€/kWh)')),
                ('maintenance_cost_annual', models.FloatField(blank=True, default=0, help_text='Ετήσιο κόστος συντήρησης νέων λαμπτήρων', null=True, verbose_name='Ετήσιο κόστος συντήρησης (€)')),
                ('lifespan_years', models.FloatField(blank=True, default=10, help_text='Αναμενόμενη διάρκεια ζωής νέων λαμπτήρων', null=True, verbose_name='Διάρκεια ζωής (έτη)')),
                ('energy_savings_kwh', models.FloatField(blank=True, help_text='Ετήσια ενεργειακή εξοικονόμηση από την αντικατάσταση', null=True, verbose_name='Ετήσια ενεργειακή εξοικονόμηση (kWh)')),
                ('total_investment_cost', models.FloatField(blank=True, help_text='Συνολικό κόστος αντικατάστασης λαμπτήρων', null=True, verbose_name='Συνολικό κόστος επένδυσης (€)')),
                ('annual_cost_savings', models.FloatField(blank=True, help_text='Ετήσια εξοικονόμηση σε κόστος ενέργειας', null=True, verbose_name='Ετήσια οικονομική εξοικονόμηση (€)')),
                ('payback_period', models.FloatField(blank=True, help_text='Χρόνος απόσβεσης της επένδυσης', null=True, verbose_name='Περίοδος αποπληρωμής (έτη)')),
                ('net_present_value', models.FloatField(blank=True, help_text='NPV της επένδυσης', null=True, verbose_name='Καθαρή παρούσα αξία (€)')),
                ('internal_rate_of_return', models.FloatField(blank=True, help_text='IRR της επένδυσης', null=True, verbose_name='Εσωτερικός βαθμός απόδοσης (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία ενημέρωσης')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building', verbose_name='Κτίριο')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Έργο')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Αντικατάσταση Λαμπτήρων',
                'verbose_name_plural': 'Αντικαταστάσεις Λαμπτήρων',
                'ordering': ['-created_at'],
            },
        ),
    ]
