# Generated by Django 4.2.3 on 2025-06-21 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_project_buildings_count'),
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalZone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thermal_zone_usage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Χρήση θερμικής ζώνης')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
                ('space_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Κατάσταση χώρου')),
                ('floor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Όροφος')),
                ('total_thermal_zone_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Συνολική επιφάνεια θερμικής ζώνης (m²)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία τελευταίας ενημέρωσης')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_zones', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_zones', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thermal_zones', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Θερμική Ζώνη',
                'verbose_name_plural': 'Θερμικές Ζώνες',
                'ordering': ['-created_at'],
            },
        ),
    ]
