# Generated by Django 5.1.6 on 2025-07-27 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioningAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy_cost_kwh', models.FloatField(default=0, help_text='Κόστος ενέργειας (€/kWh)')),
                ('maintenance_cost_annual', models.FloatField(default=0, help_text='Ετήσιο κόστος συντήρησης (€)')),
                ('lifespan_years', models.IntegerField(default=15, help_text='Διάρκεια ζωής (έτη)')),
                ('discount_rate', models.FloatField(default=5.0, help_text='Επιτόκιο αναγωγής (%)')),
                ('total_old_consumption', models.FloatField(default=0, help_text='Συνολική παλαιά κατανάλωση kWh')),
                ('total_new_consumption', models.FloatField(default=0, help_text='Συνολική νέα κατανάλωση kWh')),
                ('energy_savings_kwh', models.FloatField(default=0, help_text='Ενεργειακή εξοικονόμηση kWh')),
                ('total_investment_cost', models.FloatField(default=0, help_text='Συνολικό κόστος επένδυσης (€)')),
                ('annual_cost_savings', models.FloatField(default=0, help_text='Ετήσια οικονομική εξοικονόμηση (€)')),
                ('payback_period', models.FloatField(default=0, help_text='Περίοδος αποπληρωμής (έτη)')),
                ('net_present_value', models.FloatField(default=0, help_text='Καθαρή παρούσα αξία (€)')),
                ('internal_rate_of_return', models.FloatField(default=0, help_text='Εσωτερικός βαθμός απόδοσης (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_analyses', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ac_analyses', to='project.project')),
            ],
            options={
                'verbose_name': 'Ανάλυση Κλιματιστικών',
                'verbose_name_plural': 'Αναλύσεις Κλιματιστικών',
                'db_table': 'air_conditioning_analysis',
            },
        ),
        migrations.CreateModel(
            name='NewAirConditioning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('btu_type', models.IntegerField(help_text='Τύπος σε BTU')),
                ('cop_percentage', models.FloatField(help_text='Συντελεστής απόδοσης θέρμανσης (COP) %')),
                ('eer_percentage', models.FloatField(help_text='Συντελεστής απόδοσης ψύξης (EER) %')),
                ('heating_hours_per_year', models.IntegerField(help_text='Ώρες λειτουργίας θέρμανσης ανά έτος')),
                ('cooling_hours_per_year', models.IntegerField(help_text='Ώρες λειτουργίας ψύξης ανά έτος')),
                ('quantity', models.IntegerField(help_text='Πλήθος κλιματιστικών')),
                ('cost_per_unit', models.FloatField(default=0, help_text='Κόστος ανά μονάδα (€)')),
                ('installation_cost', models.FloatField(default=0, help_text='Κόστος εγκατάστασης (€)')),
                ('heating_consumption_kwh', models.FloatField(default=0, help_text='Κατανάλωση θέρμανσης kWh')),
                ('cooling_consumption_kwh', models.FloatField(default=0, help_text='Κατανάλωση ψύξης kWh')),
                ('total_consumption_kwh', models.FloatField(default=0, help_text='Συνολική κατανάλωση kWh')),
                ('total_cost', models.FloatField(default=0, help_text='Συνολικό κόστος (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_air_conditionings', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_air_conditionings', to='project.project')),
            ],
            options={
                'verbose_name': 'Νέο Κλιματιστικό',
                'verbose_name_plural': 'Νέα Κλιματιστικά',
                'db_table': 'new_air_conditioning',
            },
        ),
        migrations.CreateModel(
            name='OldAirConditioning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('btu_type', models.IntegerField(help_text='Τύπος σε BTU')),
                ('cop_percentage', models.FloatField(help_text='Συντελεστής απόδοσης θέρμανσης (COP) %')),
                ('eer_percentage', models.FloatField(help_text='Συντελεστής απόδοσης ψύξης (EER) %')),
                ('heating_hours_per_year', models.IntegerField(help_text='Ώρες λειτουργίας θέρμανσης ανά έτος')),
                ('cooling_hours_per_year', models.IntegerField(help_text='Ώρες λειτουργίας ψύξης ανά έτος')),
                ('quantity', models.IntegerField(help_text='Πλήθος κλιματιστικών')),
                ('heating_consumption_kwh', models.FloatField(default=0, help_text='Κατανάλωση θέρμανσης kWh')),
                ('cooling_consumption_kwh', models.FloatField(default=0, help_text='Κατανάλωση ψύξης kWh')),
                ('total_consumption_kwh', models.FloatField(default=0, help_text='Συνολική κατανάλωση kWh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_air_conditionings', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_air_conditionings', to='project.project')),
            ],
            options={
                'verbose_name': 'Παλαιό Κλιματιστικό',
                'verbose_name_plural': 'Παλαιά Κλιματιστικά',
                'db_table': 'old_air_conditioning',
            },
        ),
    ]
