# Generated by Django 5.1.6 on 2025-09-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioningReplacement', '0001_initial'),
        ('building', '0007_alter_building_prefecture'),
        ('project', '0003_project_is_submitted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airconditioninganalysis',
            unique_together={('building', 'project')},
        ),
    ]
