# Generated by Django 4.2.3 on 2025-11-12 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('building', '0007_alter_building_prefecture'),
        ('project', '0003_project_is_submitted'),
        ('airConditioningReplacement', '0002_alter_airconditioninganalysis_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airconditioninganalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='airconditioninganalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='newairconditioning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='oldairconditioning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterUniqueTogether(
            name='airconditioninganalysis',
            unique_together={('building', 'project', 'user')},
        ),
    ]
