# Generated by Django 4.2.3 on 2025-11-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airConditioningReplacement', '0003_alter_airconditioninganalysis_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airconditioninganalysis',
            name='annual_cost_savings',
        ),
        migrations.RemoveField(
            model_name='airconditioninganalysis',
            name='maintenance_cost_annual',
        ),
        migrations.AddField(
            model_name='airconditioninganalysis',
            name='annual_economic_benefit',
            field=models.FloatField(default=0, help_text='Ετήσιο οικονομικό όφελος (€)'),
        ),
        migrations.AddField(
            model_name='airconditioninganalysis',
            name='annual_energy_savings',
            field=models.FloatField(default=0, help_text='Ετήσια ενεργειακή εξοικονόμηση (€)'),
        ),
        migrations.AlterField(
            model_name='airconditioninganalysis',
            name='discount_rate',
            field=models.FloatField(default=5.0, help_text='Προεξοφλητικός συντελεστής (%)'),
        ),
        migrations.AlterField(
            model_name='airconditioninganalysis',
            name='energy_cost_kwh',
            field=models.FloatField(blank=True, default=0, help_text='Κόστος ενέργειας (€/kWh) - Λαμβάνεται από το έργο', null=True),
        ),
        migrations.AlterField(
            model_name='airconditioninganalysis',
            name='lifespan_years',
            field=models.IntegerField(default=20, help_text='Χρονικό διάστημα αξιολόγησης (έτη)'),
        ),
    ]
