# Generated by Django 5.1.6 on 2025-08-01 12:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('exterior', 'Exterior Views'), ('interior', 'Interior Views'), ('systems', 'Building Systems'), ('construction', 'Construction Details'), ('documentation', 'Documentation'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True)),
                ('image', models.ImageField(help_text='Maximum file size: 10MB. Allowed formats: JPG, JPEG, PNG, GIF', upload_to='building_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='project.project')),
            ],
            options={
                'verbose_name': 'Building Image',
                'verbose_name_plural': 'Building Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
