# Generated by Django 5.1.6 on 2025-08-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildingImages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingimage',
            name='image',
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='image_data',
            field=models.BinaryField(default=b'', help_text='Image binary data. Maximum file size: 10MB. Allowed formats: JPG, JPEG, PNG, GIF'),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='image_name',
            field=models.CharField(default='', help_text='Original filename', max_length=255),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='image_size',
            field=models.PositiveIntegerField(default=0, help_text='Image file size in bytes'),
        ),
        migrations.AddField(
            model_name='buildingimage',
            name='image_type',
            field=models.CharField(default='image/jpeg', help_text='Image MIME type (e.g., image/jpeg)', max_length=50),
        ),
    ]
