# Generated by Django 4.2.3 on 2025-11-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buildingImages', '0002_remove_buildingimage_image_buildingimage_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
