# Generated by Django 4.2.3 on 2025-11-20 08:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buildingImages', '0003_buildingimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingimage',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
