# Generated by Django 5.1.6 on 2025-06-07 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarCollector',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solar_collector_usage', models.CharField(blank=True, max_length=255, null=True, verbose_name='Χρήση ηλιακών συλλεκτών')),
                ('solar_collector_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Τύπος ηλιακού συλλέκτη')),
                ('collector_surface_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Επιφάνεια ηλιακών συλλεκτών (m²)')),
                ('hot_water_storage_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Χωρητικότητα δοχείου αποθήκευσης για Ζ.Ν.Χ. (L)')),
                ('heating_storage_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Χωρητικότητα δοχείου αποθήκευσης για τη θέρμανση χώρων (L)')),
                ('distribution_network_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Κατάσταση δικτύου διανομής (που περνά από μη θερμαινόμενους χώρους)')),
                ('terminal_units_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Θέση τερματικών μονάδων')),
                ('collector_accessibility', models.CharField(blank=True, max_length=255, null=True, verbose_name='Δυνατότητα πρόσβασης στους ηλιακούς συλλέκτες')),
                ('storage_tank_condition', models.CharField(blank=True, max_length=255, null=True, verbose_name='Κατάσταση δοχείου αποθήκευσης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_collectors', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_collectors', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_collectors', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
        ),
    ]
