# Generated by Django 5.1.6 on 2025-08-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarCollectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarcollector',
            name='net_present_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Αυτόματος υπολογισμός NPV με προεξοφλητικό συντελεστή', max_digits=12, null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)'),
        ),
    ]
