# Generated by Django 5.1.6 on 2025-09-30 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('solarCollectors', '0002_solarcollector_net_present_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solarcollector',
            options={'verbose_name': 'Ηλιακός Συλλέκτης', 'verbose_name_plural': 'Ηλιακοί Συλλέκτες'},
        ),
        migrations.AlterUniqueTogether(
            name='solarcollector',
            unique_together={('building', 'user')},
        ),
    ]
