# Generated by Django 5.1.6 on 2025-07-22 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowReplacement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_thermal_conductivity', models.FloatField(help_text='Συντελεστής θερμικής αγωγιμότητας παλαιών υαλοπινάκων', verbose_name='Παλαιός συντελεστής θερμικής αγωγιμότητας (W/m²K)')),
                ('new_thermal_conductivity', models.FloatField(help_text='Συντελεστής θερμικής αγωγιμότητας νέων υαλοπινάκων', verbose_name='Νέος συντελεστής θερμικής αγωγιμότητας (W/m²K)')),
                ('window_area', models.FloatField(help_text='Συνολική επιφάνεια υαλοπινάκων προς αντικατάσταση', verbose_name='Επιφάνεια υαλοπινάκων (m²)')),
                ('old_losses_summer', models.FloatField(blank=True, help_text='Ενεργειακές απώλειες με παλαιούς υαλοπίνακες κατά τους θερινούς μήνες', null=True, verbose_name='Απώλειες πριν - Θερινοί Μήνες (kWh)')),
                ('old_losses_winter', models.FloatField(blank=True, help_text='Ενεργειακές απώλειες με παλαιούς υαλοπίνακες κατά τους χειμερινούς μήνες', null=True, verbose_name='Απώλειες πριν - Χειμερινοί Μήνες (kWh)')),
                ('new_losses_summer', models.FloatField(blank=True, help_text='Ενεργειακές απώλειες με νέους υαλοπίνακες κατά τους θερινούς μήνες', null=True, verbose_name='Απώλειες μετά - Θερινοί Μήνες (kWh)')),
                ('new_losses_winter', models.FloatField(blank=True, help_text='Ενεργειακές απώλειες με νέους υαλοπίνακες κατά τους χειμερινούς μήνες', null=True, verbose_name='Απώλειες μετά - Χειμερινοί Μήνες (kWh)')),
                ('cost_per_sqm', models.FloatField(blank=True, help_text='Κόστος αντικατάστασης ανά τετραγωνικό μέτρο', null=True, verbose_name='Κόστος ανά m² (€/m²)')),
                ('energy_cost_kwh', models.FloatField(blank=True, help_text='Κόστος ενεργειακής μονάδας', null=True, verbose_name='Κόστος ενέργειας (€/kWh)')),
                ('maintenance_cost_annual', models.FloatField(blank=True, default=0, help_text='Ετήσιο κόστος συντήρησης νέων υαλοπινάκων', null=True, verbose_name='Ετήσιο κόστος συντήρησης (€)')),
                ('lifespan_years', models.FloatField(blank=True, default=20, help_text='Αναμενόμενη διάρκεια ζωής νέων υαλοπινάκων', null=True, verbose_name='Διάρκεια ζωής (έτη)')),
                ('energy_savings_summer', models.FloatField(blank=True, help_text='Ετήσια ενεργειακή εξοικονόμηση κατά τους θερινούς μήνες', null=True, verbose_name='Ενεργειακή εξοικονόμηση καλοκαίρι (kWh)')),
                ('energy_savings_winter', models.FloatField(blank=True, help_text='Ετήσια ενεργειακή εξοικονόμηση κατά τους χειμερινούς μήνες', null=True, verbose_name='Ενεργειακή εξοικονόμηση χειμώνα (kWh)')),
                ('total_energy_savings', models.FloatField(blank=True, help_text='Συνολική ετήσια ενεργειακή εξοικονόμηση', null=True, verbose_name='Συνολική ετήσια ενεργειακή εξοικονόμηση (kWh)')),
                ('annual_cost_savings', models.FloatField(blank=True, help_text='Ετήσια εξοικονόμηση σε κόστος ενέργειας', null=True, verbose_name='Ετήσια οικονομική εξοικονόμηση (€)')),
                ('total_investment_cost', models.FloatField(blank=True, help_text='Συνολικό κόστος αντικατάστασης υαλοπινάκων', null=True, verbose_name='Συνολικό κόστος επένδυσης (€)')),
                ('payback_period', models.FloatField(blank=True, help_text='Χρόνος απόσβεσης της επένδυσης', null=True, verbose_name='Περίοδος αποπληρωμής (έτη)')),
                ('net_present_value', models.FloatField(blank=True, help_text='NPV της επένδυσης', null=True, verbose_name='Καθαρή παρούσα αξία (€)')),
                ('internal_rate_of_return', models.FloatField(blank=True, help_text='IRR της επένδυσης', null=True, verbose_name='Εσωτερικός βαθμός απόδοσης (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία ενημέρωσης')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building', verbose_name='Κτίριο')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Έργο')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Αντικατάσταση Υαλοπινάκων',
                'verbose_name_plural': 'Αντικαταστάσεις Υαλοπινάκων',
                'ordering': ['-created_at'],
            },
        ),
    ]
