# Generated by Django 5.1.6 on 2025-09-30 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('windowReplacement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='windowreplacement',
            unique_together={('building', 'user')},
        ),
    ]
