# Generated by Django 4.2.3 on 2025-11-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowReplacement', '0002_alter_windowreplacement_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='windowreplacement',
            name='discount_rate',
            field=models.FloatField(blank=True, default=5.0, help_text='Επιτόκιο αναγωγής για υπολογισμούς NPV', null=True, verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
    ]
