# Generated by Django 4.2.3 on 2025-11-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowReplacement', '0003_windowreplacement_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowreplacement',
            name='cost_per_sqm',
            field=models.FloatField(default=0, help_text='Κόστος αντικατάστασης ανά τετραγωνικό μέτρο', verbose_name='Κόστος ανά m² (€/m²)'),
        ),
    ]
