# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windowReplacement', '0005_windowreplacement_discounted_payback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windowreplacement',
            name='discounted_payback_period',
            field=models.FloatField(blank=True, help_text='Χρόνος απόσβεσης με προεξόφληση', null=True, verbose_name='Προεξοφλημένη περίοδος αποπληρωμής (έτη)'),
        ),
    ]
