# Generated by Django 5.1.6 on 2025-05-18 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingSystem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exchanger_type', models.CharField(blank=True, max_length=100, null=True)),
                ('power_kw', models.FloatField(blank=True, null=True)),
                ('construction_year', models.IntegerField(blank=True, null=True)),
                ('cop', models.FloatField(blank=True, null=True)),
                ('distribution_network_state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_systems', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_systems', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heating_systems', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
        ),
    ]
