# Generated by Django 5.1.6 on 2025-09-30 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('heatingSystem', '0002_heatingsystem_central_boiler_system_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatingsystem',
            options={'verbose_name': 'Σύστημα Θέρμανσης', 'verbose_name_plural': 'Συστήματα Θέρμανσης'},
        ),
        migrations.AlterUniqueTogether(
            name='heatingsystem',
            unique_together={('building', 'user')},
        ),
    ]
