# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatingSystem', '0003_alter_heatingsystem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingsystem',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ισχύς (W)'),
        ),
    ]
