# Generated by Django 5.1.6 on 2025-07-07 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Νομού')),
                ('zone', models.CharField(choices=[('A', 'Ζώνη Α'), ('B', 'Ζώνη Β'), ('C', 'Ζώνη Γ'), ('D', 'Ζώνη Δ')], help_text='Ενεργειακή ζώνη σύμφωνα με τον ελληνικό κανονισμό', max_length=1, verbose_name='Ενεργειακή Ζώνη')),
                ('temperature_winter', models.FloatField(blank=True, help_text='Μέση θερμοκρασία χειμώνα σε βαθμούς Κελσίου', null=True, verbose_name='Θερμοκρασία Χειμώνα (°C)')),
                ('temperature_summer', models.FloatField(blank=True, help_text='Μέση θερμοκρασία καλοκαιριού σε βαθμούς Κελσίου', null=True, verbose_name='Θερμοκρασία Καλοκαιριού (°C)')),
                ('is_active', models.BooleanField(default=True, help_text='Αν ο νομός είναι διαθέσιμος για χρήση', verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('created_by', models.ForeignKey(blank=True, help_text='Μόνο admin μπορεί να δημιουργήσει νομούς', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργός')),
            ],
            options={
                'verbose_name': 'Νομός',
                'verbose_name_plural': 'Νομοί',
                'ordering': ['name'],
            },
        ),
    ]
