# Generated by Django 4.2.3 on 2025-11-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='solar_radiation',
            field=models.FloatField(blank=True, default=5.0, help_text='Μέση ημερήσια ηλιακή ακτινοβολία για τους μήνες ψύξης', null=True, verbose_name='Μέση ημερήσια ηλιακή ακτινοβολία (kWh/m²/ημέρα)'),
        ),
    ]
