# Generated by Django 4.2.3 on 2025-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0003_auto_update_solar_radiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefecture',
            name='annual_solar_radiation',
            field=models.FloatField(blank=True, default=1600.0, help_text='Ετήσια ηλιακή ακτινοβολία για υπολογισμό φωτοβολταϊκών συστημάτων', null=True, verbose_name='Ετήσια ηλιακή ακτινοβολία (kWh/m²/έτος)'),
        ),
    ]
