# Generated by Django 4.2.3 on 2025-11-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefectures', '0004_prefecture_annual_solar_radiation'),
    ]

    operations = [
    ]
