# Generated by Django 4.2.3 on 2025-06-21 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energyConsumption', '0004_alter_energyconsumption_kwh_equivalent'),
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_project_buildings_count'),
        ('thermalZone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalConsumption',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumption_type', models.CharField(choices=[('lighting', 'Φωτισμός'), ('air_conditioning', 'Κλιματισμός'), ('other_electrical_devices', 'Άλλες ηλεκτρικές συσκευές')], max_length=50, verbose_name='Τύπος κατανάλωσης')),
                ('period', models.CharField(blank=True, max_length=255, null=True, verbose_name='Περίοδος')),
                ('load_type', models.CharField(blank=True, choices=[('continuous', 'Συνεχής'), ('intermittent', 'Διαλείπων'), ('peak', 'Αιχμής'), ('base', 'Βάσης')], max_length=50, null=True, verbose_name='Τύπος φορτίου')),
                ('load_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ισχύς φορτίου (W)')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Πλήθος')),
                ('operating_hours_per_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ώρες λειτουργίας ανά έτος')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία τελευταίας ενημέρωσης')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_consumptions', to='building.building')),
                ('energy_consumption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_consumptions', to='energyConsumption.energyconsumption', verbose_name='Τύπος κατανάλωσης (Energy Consumption)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_consumptions', to='project.project')),
                ('thermal_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_consumptions', to='thermalZone.thermalzone', verbose_name='Θερμική ζώνη')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_consumptions', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ηλεκτρική Κατανάλωση',
                'verbose_name_plural': 'Ηλεκτρικές Καταναλώσεις',
                'ordering': ['-created_at'],
            },
        ),
    ]
