# Generated by Django 5.1.6 on 2025-06-22 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricalConsumption', '0001_initial'),
        ('energyConsumption', '0004_alter_energyconsumption_kwh_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricalconsumption',
            name='energy_consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electrical_consumptions', to='energyConsumption.energyconsumption', verbose_name='Αναφορά Ενεργειακής Κατανάλωσης'),
        ),
    ]
