# Generated by Django 5.1.6 on 2025-11-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricalConsumption', '0002_alter_electricalconsumption_energy_consumption'),
        ('electricalConsumption', '0003_convert_load_power_kw_to_w'),
    ]

    operations = [
    ]
