# Generated by Django 5.1.6 on 2025-05-10 08:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Σύνολο Κτιρίου')),
                ('usage', models.CharField(help_text='π.χ. Νοσοκομείο, Κλινικές', max_length=100, verbose_name='Χρήση Κτιρίου')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Έτος Κατασκευής')),
                ('address', models.CharField(max_length=200, verbose_name='Διεύθυνση')),
                ('is_insulated', models.BooleanField(default=False, verbose_name='Μονωμένο')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Πιστοποιημένο')),
                ('energy_class', models.CharField(blank=True, max_length=50, verbose_name='Ενεργειακή Κλάση')),
                ('orientation', models.CharField(blank=True, help_text='π.χ. Βόρειος, Νότιος, Ανατολικός, Δυτικός', max_length=50, verbose_name='Προσανατολισμός')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Συνολική Επιφάνεια (m²)')),
                ('examined_area', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξεταζόμενη Επιφάνεια (m²)')),
                ('floors_examined', models.PositiveIntegerField(default=1, verbose_name='Αριθμός Εξεταζόμενων Ορόφων')),
                ('floor_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ύψος Ορόφου (m)')),
                ('construction_type', models.CharField(blank=True, help_text='Μέθοδος/υλικά κατασκευής', max_length=100, verbose_name='Τύπος Κατασκευής')),
                ('free_facades', models.PositiveIntegerField(blank=True, help_text='Αριθμός εκτεθειμένων εξωτερικών τοίχων (0-4)', null=True, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Ελεύθερες Όψεις')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Υψόμετρο κτιρίου από τη στάθμη της θάλασσας', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Υψόμετρο (m)')),
                ('non_operating_days', models.CharField(blank=True, help_text='π.χ. Σαββατοκύριακα, Αργίες', max_length=200, verbose_name='Ημέρες Μη Λειτουργίας')),
                ('operating_hours', models.CharField(blank=True, help_text='π.χ. 9:00-17:00', max_length=100, verbose_name='Ωράριο Λειτουργίας')),
                ('occupants', models.PositiveIntegerField(blank=True, help_text='Μέσος αριθμός ατόμων στο κτίριο', null=True, verbose_name='Αριθμός Ατόμων')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
