# Generated by Django 4.2.3 on 2025-05-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
    ]
