# Generated by Django 5.1.6 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_energy_zone_building_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='energy_zone',
            field=models.CharField(max_length=1, verbose_name='Ενεργειακή Ζώνη'),
        ),
        migrations.AlterField(
            model_name='building',
            name='prefecture',
            field=models.CharField(max_length=100, verbose_name='Νομός'),
        ),
    ]
