# Generated by Django 4.2.3 on 2025-05-06 19:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20250506_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='co2_ppm',
        ),
        migrations.RemoveField(
            model_name='building',
            name='exhaust_temperature',
        ),
        migrations.RemoveField(
            model_name='building',
            name='no_ppm',
        ),
        migrations.RemoveField(
            model_name='building',
            name='nox_ppm',
        ),
        migrations.RemoveField(
            model_name='building',
            name='room_temperature',
        ),
        migrations.RemoveField(
            model_name='building',
            name='smoke_scale',
        ),
        migrations.AddField(
            model_name='building',
            name='altitude',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Υψόμετρο κτιρίου από τη στάθμη της θάλασσας', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Υψόμετρο (m)'),
        ),
        migrations.AddField(
            model_name='building',
            name='construction_type',
            field=models.CharField(blank=True, help_text='Μέθοδος/υλικά κατασκευής', max_length=100, verbose_name='Τύπος Κατασκευής'),
        ),
        migrations.AddField(
            model_name='building',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία Δημιουργίας'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='floor_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ύψος Ορόφου (m)'),
        ),
        migrations.AddField(
            model_name='building',
            name='free_facades',
            field=models.PositiveIntegerField(blank=True, help_text='Αριθμός εκτεθειμένων εξωτερικών τοίχων (0-4)', null=True, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Ελεύθερες Όψεις'),
        ),
        migrations.AddField(
            model_name='building',
            name='non_operating_days',
            field=models.CharField(blank=True, help_text='π.χ. Σαββατοκύριακα, Αργίες', max_length=200, verbose_name='Ημέρες Μη Λειτουργίας'),
        ),
        migrations.AddField(
            model_name='building',
            name='occupants',
            field=models.PositiveIntegerField(blank=True, help_text='Μέσος αριθμός ατόμων στο κτίριο', null=True, verbose_name='Αριθμός Ατόμων'),
        ),
        migrations.AddField(
            model_name='building',
            name='operating_hours',
            field=models.CharField(blank=True, help_text='π.χ. 9:00-17:00', max_length=100, verbose_name='Ωράριο Λειτουργίας'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(verbose_name='Περιγραφή'),
        ),
    ]
