# Generated by Django 5.1.6 on 2025-07-07 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='prefecture_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='prefectures.prefecture', verbose_name='Νομός (Νέο)'),
        ),
    ]
