# Generated by Django 5.1.6 on 2025-07-07 10:05

from django.db import migrations


def populate_prefecture_fk(apps, schema_editor):
    """
    Populate the new prefecture ForeignKey field from the old CharField field
    """
    Building = apps.get_model('building', 'Building')
    Prefecture = apps.get_model('prefectures', 'Prefecture')
    
    for building in Building.objects.all():
        try:
            # Find the prefecture by name
            prefecture = Prefecture.objects.get(name=building.prefecture)
            building.prefecture_new = prefecture
            building.save()
            print(f"Updated building {building.name} with prefecture {prefecture.name}")
        except Prefecture.DoesNotExist:
            print(f"Warning: Prefecture '{building.prefecture}' not found for building {building.name}")
        except Exception as e:
            print(f"Error updating building {building.name}: {e}")


def reverse_populate_prefecture_fk(apps, schema_editor):
    """
    Reverse operation - populate the old CharField from the ForeignKey
    """
    Building = apps.get_model('building', 'Building')
    
    for building in Building.objects.all():
        if building.prefecture_new:
            building.prefecture = building.prefecture_new.name
            building.save()


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_add_prefecture_fk'),
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            populate_prefecture_fk,
            reverse_populate_prefecture_fk,
        ),
    ]
