# Generated by Django 5.1.6 on 2025-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_populate_prefecture_fk'),
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='prefecture',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='prefecture_new',
            new_name='prefecture',
        ),
        migrations.AlterField(
            model_name='building',
            name='energy_zone',
            field=models.CharField(editable=False, max_length=1, verbose_name='Ενεργειακή Ζώνη'),
        ),
    ]
