# Generated by Django 5.1.6 on 2025-07-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_finalize_prefecture_fk'),
        ('prefectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='prefectures.prefecture', verbose_name='Νομός'),
        ),
    ]
