# Generated by Django 5.1.6 on 2025-10-06 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericValue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Μοναδικό όνομα για την αριθμητική τιμή', max_length=200, unique=True, verbose_name='Όνομα')),
                ('value', models.FloatField(help_text='Αριθμητική τιμή', verbose_name='Τιμή')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργός')),
            ],
            options={
                'verbose_name': 'Αριθμητική Τιμή',
                'verbose_name_plural': 'Αριθμητικές Τιμές',
                'ordering': ['name'],
            },
        ),
    ]
