# Generated by Django 5.1.6 on 2025-09-28 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='density',
        ),
        migrations.RemoveField(
            model_name='material',
            name='specific_heat',
        ),
    ]
