# Generated by Django 4.2.3 on 2025-12-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_remove_density_specific_heat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('wood', 'Ξυλεία'), ('concrete', 'Σκυρόδεμα'), ('insulation', 'Μονωτικά Υλικά'), ('metal', 'Μέταλλα'), ('glass', 'Γυαλί'), ('masonry', 'Τοιχοποιία'), ('plaster', 'Επιχρίσματα'), ('stone', 'Πετρώματα'), ('roof', 'Υλικά Οροφής'), ('flooring', 'Δάπεδα'), ('other', 'Άλλα')], default='other', max_length=20, verbose_name='Κατηγορία Υλικού'),
        ),
    ]
