# Generated by Django 5.1.6 on 2025-05-10 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('energy_source', models.CharField(choices=[('biomass', 'Βιομάζα'), ('electric', 'Ηλεκτρική Ενέργεια'), ('heating_oil', 'Πετρέλαιο Θέρμανσης'), ('natural_gas', 'Φυσικό Αέριο')], max_length=20)),
                ('start_date', models.DateField(verbose_name='Από')),
                ('end_date', models.DateField(verbose_name='Έως')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profiles', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profiles', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
