# Generated by Django 5.1.6 on 2025-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyConsumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyconsumption',
            name='kwh_equivalent',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Ισοδύναμο kWh'),
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='unit',
            field=models.CharField(editable=False, max_length=10, null=True, verbose_name='Μονάδα Μέτρησης'),
        ),
    ]
