# Generated by Django 5.1.6 on 2025-05-16 13:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyConsumption', '0002_energyconsumption_kwh_equivalent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='energy_source',
            field=models.CharField(choices=[('biomass', 'Βιομάζα'), ('electricity', 'Ηλεκτρική Ενέργεια'), ('heating_oil', 'Πετρέλαιο Θέρμανσης'), ('natural_gas', 'Φυσικό Αέριο')], max_length=20),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='kwh_equivalent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Ισοδύναμο kWh'),
        ),
        migrations.AlterField(
            model_name='energyconsumption',
            name='unit',
            field=models.CharField(default=2, editable=False, max_length=10, verbose_name='Μονάδα Μέτρησης'),
            preserve_default=False,
        ),
    ]
