# Generated by Django 5.1.6 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyConsumption', '0003_alter_energyconsumption_energy_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyconsumption',
            name='kwh_equivalent',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Ισοδύναμο kWh'),
        ),
    ]
