# Generated by Django 4.2.3 on 2025-11-12 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerReplacement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='boiler_power',
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='annual_heating_consumption',
            field=models.FloatField(default=10000.0, help_text='Ετήσια κατανάλωση ενέργειας για θέρμανση του κτιρίου', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσια κατανάλωση θέρμανσης (kWh/έτος)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='new_boiler_efficiency',
            field=models.DecimalField(decimal_places=2, default=95.0, help_text='Συντελεστής απόδοσης του νέου λέβητα σε %', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Συντελεστής απόδοσης νέου λέβητα (%)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='new_boiler_power',
            field=models.FloatField(default=20.0, help_text='Ισχύς του νέου λέβητα σε kW', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ισχύς νέου λέβητα (kW)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='old_boiler_age',
            field=models.IntegerField(default=0, help_text='Ηλικία του υπάρχοντος λέβητα σε έτη', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ηλικία παλιού λέβητα (έτη)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='old_boiler_efficiency',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Συντελεστής απόδοσης του υπάρχοντος λέβητα σε %', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Συντελεστής απόδοσης παλιού λέβητα (%)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='old_boiler_power',
            field=models.FloatField(default=20.0, help_text='Ισχύς του υπάρχοντος λέβητα σε kW', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ισχύς παλιού λέβητα (kW)'),
        ),
        migrations.AlterField(
            model_name='boilerreplacement',
            name='boiler_cost',
            field=models.DecimalField(decimal_places=2, help_text='Κόστος αγοράς του νέου λέβητα', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος νέου λέβητα (€)'),
        ),
        migrations.AlterField(
            model_name='boilerreplacement',
            name='heating_energy_savings',
            field=models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός: Εξοικονόμηση από τη βελτίωση απόδοσης', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση ενέργειας θέρμανσης (kWh/έτος)'),
        ),
    ]
