# Generated by Django 4.2.3 on 2025-11-13 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerReplacement', '0002_remove_boilerreplacement_boiler_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='annual_heating_consumption',
        ),
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='energy_cost_kwh',
        ),
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='heating_energy_savings',
        ),
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='new_boiler_power',
        ),
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='old_boiler_age',
        ),
        migrations.RemoveField(
            model_name='boilerreplacement',
            name='old_boiler_power',
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='annual_heating_consumption_liters',
            field=models.FloatField(default=1000.0, help_text='Ετήσια κατανάλωση πετρελαίου για θέρμανση του κτιρίου σε λίτρα', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσια κατανάλωση θέρμανσης (λίτρα/έτος)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='heating_oil_savings_liters',
            field=models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός: Εξοικονόμηση πετρελαίου από τη βελτίωση απόδοσης', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση πετρελαίου θέρμανσης (λίτρα/έτος)'),
        ),
        migrations.AddField(
            model_name='boilerreplacement',
            name='oil_price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Τιμή πετρελαίου ανά λίτρο (από τα στοιχεία του έργου)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή πετρελαίου (€/λίτρο)'),
        ),
    ]
