# Generated by Django 5.1.6 on 2025-05-16 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerDetail',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nominal_power', models.FloatField(verbose_name='Ονομαστική Ισχύς (kW)')),
                ('internal_efficiency', models.FloatField(verbose_name='Εσωτερικός Βαθμός Απόδοσης (%)')),
                ('manufacturing_year', models.IntegerField(verbose_name='Έτος Κατασκευής')),
                ('nitrogen_monoxide', models.FloatField(verbose_name='Μονοξείδιο του Αζώτου - NO (ppm)')),
                ('nitrogen_oxides', models.FloatField(verbose_name='Οξείδια του Αζώτου - NOx (ppm)')),
                ('exhaust_temperature', models.FloatField(verbose_name='Θερμοκρασία Καυσαερίων (°C)')),
                ('smoke_scale', models.IntegerField(verbose_name='Καπνός (Brigon smoke scale 0-9)')),
                ('room_temperature', models.FloatField(verbose_name='Θερμοκρασία Χώρου (°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boiler_details', to='building.building')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
