# Generated by Django 5.1.6 on 2025-05-16 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerDetail', '0001_initial'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boilerdetail',
            options={},
        ),
        migrations.AddField(
            model_name='boilerdetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boiler_details', to='project.project'),
        ),
        migrations.AddField(
            model_name='boilerdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='exhaust_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='internal_efficiency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='manufacturing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nitrogen_monoxide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nitrogen_oxides',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nominal_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='room_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='smoke_scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
