# Generated by Django 5.1.6 on 2025-05-17 17:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerDetail', '0002_alter_boilerdetail_options_boilerdetail_project_and_more'),
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerdetail',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boiler_details', to='building.building', verbose_name='Κτίριο'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='exhaust_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θερμοκρασία Καυσαερίων (°C)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='internal_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Εσωτερικός Βαθμός Απόδοσης (%)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='manufacturing_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Έτος Κατασκευής'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nitrogen_monoxide',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Βεβαιωθείτε ότι η τιμή είναι ≤ 65', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65)], verbose_name='Μονοξείδιο του Αζώτου - NO (ppm)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nitrogen_oxides',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Βεβαιωθείτε ότι η τιμή είναι ≤ 65', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65)], verbose_name='Οξείδια του Αζώτου - NOx (ppm)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='nominal_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ονομαστική Ισχύς (kW)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boiler_details', to='project.project', verbose_name='Έργο'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='room_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Θερμοκρασία Χώρου (°C)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='smoke_scale',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Βεβαιωθείτε ότι η τιμή είναι μεταξύ 0-9', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)], verbose_name='Κάπνός (Brigon smoke scale 0-9)'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Τελευταίας Ενημέρωσης'),
        ),
        migrations.AlterField(
            model_name='boilerdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boiler_details', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
    ]
