# Generated by Django 5.1.6 on 2025-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerDetail', '0003_alter_boilerdetail_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boilerdetail',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Είδος Καυσίμου'),
        ),
    ]
