# Generated by Django 5.1.6 on 2026-04-27 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerDetail', '0004_boilerdetail_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerdetail',
            name='nominal_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ονομαστική Ισχύς (W)'),
        ),
    ]
