# Generated by Django 5.1.6 on 2025-08-02 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('contact', 'Contact Added/Updated'), ('image', 'Image Added/Updated'), ('system', 'System Added/Updated'), ('material', 'Material Added/Updated'), ('energy', 'Energy Data Added/Updated'), ('calculation', 'Calculation Performed'), ('export', 'Data Exported'), ('import', 'Data Imported'), ('other', 'Other Activity')], max_length=20)),
                ('title', models.CharField(help_text='Short description of the activity', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what happened', null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='building.building')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_activities', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Building Activity',
                'verbose_name_plural': 'Building Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['building', '-created_at'], name='buildingAct_buildin_f62445_idx'), models.Index(fields=['project', '-created_at'], name='buildingAct_project_87be3e_idx'), models.Index(fields=['action_type', '-created_at'], name='buildingAct_action__c1ab5b_idx'), models.Index(fields=['user', '-created_at'], name='buildingAct_user_id_37d69d_idx')],
            },
        ),
    ]
