# Generated by Django 5.1.6 on 2025-05-10 08:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('cost_per_kwh_fuel', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Κόστος ανά kWh καυσίμου (€)')),
                ('cost_per_kwh_electricity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Κόστος ανά kWh ρεύματος (€)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
