# Generated by Django 4.2.3 on 2025-03-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_kwh_fuel', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Κόστος ανά kWh καυσίμου (€)')),
                ('cost_per_kwh_electricity', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Κόστος ανά kWh ρεύματος (€)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.user')),
            ],
        ),
    ]
