# Generated by Django 5.1.6 on 2025-08-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Έχει Υποβληθεί'),
        ),
    ]
