# Generated by Django 4.2.3 on 2025-11-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='biomass_price_per_kg',
            field=models.DecimalField(decimal_places=3, default=0.25, help_text='Τρέχουσα τιμή βιομάζας ανά κιλό', max_digits=6, verbose_name='Τιμή βιομάζας ανά kg (€)'),
        ),
        migrations.AddField(
            model_name='project',
            name='natural_gas_price_per_m3',
            field=models.DecimalField(decimal_places=3, default=0.8, help_text='Τρέχουσα τιμή φυσικού αερίου ανά κυβικό μέτρο', max_digits=6, verbose_name='Τιμή φυσικού αερίου ανά m³ (€)'),
        ),
        migrations.AddField(
            model_name='project',
            name='oil_price_per_liter',
            field=models.DecimalField(decimal_places=3, default=1.2, help_text='Τρέχουσα τιμή πετρελαίου θέρμανσης ανά λίτρο', max_digits=6, verbose_name='Τιμή πετρελαίου ανά λίτρο (€)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_per_kwh_fuel',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Legacy field - χρησιμοποιείται για παλαιότερα δεδομένα', max_digits=6, null=True, verbose_name='Κόστος ανά kWh καυσίμου (€)'),
        ),
    ]
