# Generated by Django 4.2.3 on 2025-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_biomass_price_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost_per_kwh_fuel',
        ),
        migrations.AlterField(
            model_name='project',
            name='biomass_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Τρέχουσα τιμή βιομάζας ανά κιλό', max_digits=6, null=True, verbose_name='Τιμή βιομάζας ανά kg (€)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='natural_gas_price_per_m3',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Τρέχουσα τιμή φυσικού αερίου ανά κυβικό μέτρο', max_digits=6, null=True, verbose_name='Τιμή φυσικού αερίου ανά m³ (€)'),
        ),
    ]
