# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_cost_per_kwh_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='natural_gas_price_per_m3',
            field=models.DecimalField(decimal_places=3, default=0.8, help_text='Τρέχουσα τιμή φυσικού αερίου ανά κυβικό μέτρο', max_digits=6, verbose_name='Τιμή φυσικού αερίου ανά m³ (€)'),
        ),
    ]
