# Generated by Django 5.1.6 on 2025-07-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotWaterUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solar_collectors_quantity', models.IntegerField(default=0)),
                ('solar_collectors_unit_price', models.FloatField(default=0.0)),
                ('metal_support_bases_quantity', models.IntegerField(default=0)),
                ('metal_support_bases_unit_price', models.FloatField(default=0.0)),
                ('solar_system_quantity', models.IntegerField(default=1)),
                ('solar_system_unit_price', models.FloatField(default=0.0)),
                ('insulated_pipes_quantity', models.IntegerField(default=0)),
                ('insulated_pipes_unit_price', models.FloatField(default=0.0)),
                ('central_heater_installation_quantity', models.IntegerField(default=1)),
                ('central_heater_installation_unit_price', models.FloatField(default=0.0)),
                ('electric_heater_power', models.FloatField(default=0.0)),
                ('operating_hours_per_year', models.FloatField(default=0.0)),
                ('solar_utilization_percentage', models.FloatField(default=80.0)),
                ('energy_cost_kwh', models.FloatField(default=0.0)),
                ('lifespan_years', models.IntegerField(default=10)),
                ('solar_collectors_subtotal', models.FloatField(default=0.0)),
                ('metal_support_bases_subtotal', models.FloatField(default=0.0)),
                ('solar_system_subtotal', models.FloatField(default=0.0)),
                ('insulated_pipes_subtotal', models.FloatField(default=0.0)),
                ('central_heater_installation_subtotal', models.FloatField(default=0.0)),
                ('total_investment_cost', models.FloatField(default=0.0)),
                ('annual_energy_consumption_kwh', models.FloatField(default=0.0)),
                ('annual_solar_savings_kwh', models.FloatField(default=0.0)),
                ('annual_economic_benefit', models.FloatField(default=0.0)),
                ('payback_period', models.FloatField(default=0.0)),
                ('net_present_value', models.FloatField(default=0.0)),
                ('internal_rate_of_return', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'hot_water_upgrade',
                'ordering': ['-created_at'],
            },
        ),
    ]
