# Generated by Django 5.1.6 on 2025-09-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotWaterUpgrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotwaterupgrade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Αναβάθμιση Ζεστού Νερού', 'verbose_name_plural': 'Αναβαθμίσεις Ζεστού Νερού'},
        ),
        migrations.AlterUniqueTogether(
            name='hotwaterupgrade',
            unique_together={('building', 'project')},
        ),
    ]
