# Generated by Django 4.2.3 on 2025-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotWaterUpgrade', '0002_alter_hotwaterupgrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwaterupgrade',
            name='annual_operating_expenses',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hotwaterupgrade',
            name='discount_rate',
            field=models.FloatField(default=5.0),
        ),
    ]
