# Generated by Django 4.2.3 on 2025-11-20 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotWaterUpgrade', '0003_hotwaterupgrade_annual_operating_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotwaterupgrade',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
