# Generated by Django 4.2.3 on 2025-11-20 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotWaterUpgrade', '0006_alter_hotwaterupgrade_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotwaterupgrade',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotwaterupgrade',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
