# Generated by Django 5.1.6 on 2025-09-30 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('materials', '0003_remove_density_specific_heat'),
        ('project', '0003_project_is_submitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofThermalInsulation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('u_coefficient', models.FloatField(default=0.0, help_text='Υπολογιζόμενος συντελεστής θερμοπερατότητας για την οροφή', verbose_name='Συντελεστής Θερμοπερατότητας U (W/m²K)')),
                ('winter_hourly_losses', models.FloatField(blank=True, help_text='Ωριαίες απώλειες κατά τους χειμερινούς μήνες', null=True, verbose_name='Χειμερινές Ωριαίες Απώλειες (kW)')),
                ('summer_hourly_losses', models.FloatField(blank=True, help_text='Ωριαίες απώλειες κατά τους θερινούς μήνες', null=True, verbose_name='Καλοκαιρινές Ωριαίες Απώλειες (kW)')),
                ('heating_hours_per_year', models.IntegerField(blank=True, help_text='Συνολικές ώρες θέρμανσης ανά έτος', null=True, verbose_name='Ώρες Θέρμανσης/Έτος')),
                ('cooling_hours_per_year', models.IntegerField(blank=True, help_text='Συνολικές ώρες ψύξης ανά έτος', null=True, verbose_name='Ώρες Ψύξης/Έτος')),
                ('total_cost', models.FloatField(blank=True, help_text='Συνολικό κόστος υλικών και εργασίας', null=True, verbose_name='Συνολικό Κόστος (€)')),
                ('annual_benefit', models.FloatField(blank=True, help_text='Ετήσια εξοικονόμηση ενέργειας σε ευρώ', null=True, verbose_name='Ετήσιο Όφελος (€)')),
                ('time_period_years', models.IntegerField(default=20, help_text='Χρονικό διάστημα για την οικονομική ανάλυση', verbose_name='Περίοδος Ανάλυσης (έτη)')),
                ('annual_operating_costs', models.FloatField(blank=True, help_text='Ετήσια κόστη συντήρησης και λειτουργίας', null=True, verbose_name='Ετήσια Λειτουργικά Κόστη (€)')),
                ('discount_rate', models.FloatField(default=5.0, help_text='Επιτόκιο για τον υπολογισμό της παρούσας αξίας', verbose_name='Επιτόκιο Προεξόφλησης (%)')),
                ('net_present_value', models.FloatField(blank=True, help_text='Καθαρή παρούσα αξία της επένδυσης', null=True, verbose_name='Καθαρή Παρούσα Αξία (€)')),
                ('payback_period', models.FloatField(blank=True, help_text='Περίοδος αποπληρωμής της επένδυσης σε έτη', null=True, verbose_name='Περίοδος αποπληρωμής (έτη)')),
                ('internal_rate_of_return', models.FloatField(blank=True, help_text='Εσωτερικός βαθμός απόδοσης της επένδυσης ως ποσοστό', null=True, verbose_name='Εσωτερικός βαθμός απόδοσης (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_thermal_insulations', to='building.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργός')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_thermal_insulations', to='project.project')),
            ],
            options={
                'verbose_name': 'Θερμομόνωση Οροφής',
                'verbose_name_plural': 'Θερμομονώσεις Οροφής',
                'ordering': ['-created_at'],
                'unique_together': {('building', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='RoofThermalInsulationMaterialLayer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('old', 'Υπάρχον Υλικό'), ('new', 'Νέο Υλικό')], help_text='Καθορίζει αν είναι υπάρχον ή νέο υλικό', max_length=10, verbose_name='Τύπος Υλικού')),
                ('surface_type', models.CharField(choices=[('external_horizontal_roof', 'Εξωτερική οριζόντια ή κεκλιμένη επιφάνεια σε επαφή με τον εξωτερικό αέρα (οροφές)'), ('external_vertical', 'Εξωτερική κατακόρυφη επιφάνεια σε επαφή με τον εξωτερικό αέρα'), ('internal_horizontal', 'Εσωτερική οριζόντια επιφάνεια'), ('internal_vertical', 'Εσωτερική κατακόρυφη επιφάνεια'), ('ground_contact', 'Επιφάνεια σε επαφή με το έδαφος')], default='external_horizontal_roof', help_text='Τύπος επιφάνειας για τον υπολογισμό θερμικής αντίστασης', max_length=30, verbose_name='Τύπος Επιφάνειας')),
                ('thickness', models.FloatField(help_text='Πάχος του υλικού σε μέτρα', verbose_name='Πάχος (m)')),
                ('surface_area', models.FloatField(help_text='Επιφάνεια εφαρμογής του υλικού', verbose_name='Επιφάνεια (m²)')),
                ('cost', models.FloatField(blank=True, help_text='Κόστος υλικού και εργασίας (μόνο για νέα υλικά)', null=True, verbose_name='Κόστος (€)')),
                ('material_name', models.CharField(blank=True, help_text='Αυτόματη συμπλήρωση από το επιλεγμένο υλικό', max_length=100, null=True, verbose_name='Όνομα Υλικού')),
                ('material_thermal_conductivity', models.FloatField(blank=True, help_text='Αυτόματη συμπλήρωση από το επιλεγμένο υλικό', null=True, verbose_name='Θερμική Αγωγιμότητα (W/mK)')),
                ('surface_type_display', models.CharField(blank=True, help_text='Περιγραφή του τύπου επιφάνειας', max_length=100, null=True, verbose_name='Επιφάνεια (Περιγραφή)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Σειρά του υλικού στη στρώση (από εσωτερικά προς εξωτερικά)', verbose_name='Σειρά')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Υλικό')),
                ('roof_thermal_insulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_layers', to='roofThermalInsulation.roofthermalinsulation')),
            ],
            options={
                'verbose_name': 'Στρώση Υλικού Θερμομόνωσης Οροφής',
                'verbose_name_plural': 'Στρώσεις Υλικών Θερμομόνωσης Οροφής',
                'ordering': ['material_type', 'order'],
            },
        ),
    ]
