# Generated by Django 5.1.6 on 2025-06-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roofThermalInsulation', '0001_initial'),
    ]

    operations = [
    ]
