# Generated by Django 5.1.6 on 2025-06-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofThermalInsulation', '0002_auto_20250628_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roofthermalinsulationmateriallayer',
            name='material_name',
            field=models.CharField(blank=True, help_text='Αυτόματη συμπλήρωση από το επιλεγμένο υλικό', max_length=100, null=True, verbose_name='Όνομα Υλικού'),
        ),
        migrations.AlterField(
            model_name='roofthermalinsulationmateriallayer',
            name='material_thermal_conductivity',
            field=models.FloatField(blank=True, help_text='Αυτόματη συμπλήρωση από το επιλεγμένο υλικό', null=True, verbose_name='Θερμική Αγωγιμότητα (W/mK)'),
        ),
        migrations.AlterField(
            model_name='roofthermalinsulationmateriallayer',
            name='surface_type_display',
            field=models.CharField(blank=True, help_text='Περιγραφή του τύπου επιφάνειας', max_length=100, null=True, verbose_name='Επιφάνεια (Περιγραφή)'),
        ),
    ]
