# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofThermalInsulation', '0002_roofthermalinsulation_discounted_payback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roofthermalinsulation',
            name='discount_rate',
            field=models.FloatField(default=5.0, help_text='Επιτόκιο για τον υπολογισμό της παρούσας αξίας', verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
    ]
