# Generated by Django 5.1.6 on 2025-09-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roofThermalInsulation', '0003_alter_roofthermalinsulationmateriallayer_material_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofthermalinsulation',
            name='internal_rate_of_return',
            field=models.FloatField(blank=True, help_text='Εσωτερικός βαθμός απόδοσης της επένδυσης ως ποσοστό', null=True, verbose_name='Εσωτερικός βαθμός απόδοσης (%)'),
        ),
        migrations.AddField(
            model_name='roofthermalinsulation',
            name='payback_period',
            field=models.FloatField(blank=True, help_text='Περίοδος αποπληρωμής της επένδυσης σε έτη', null=True, verbose_name='Περίοδος αποπληρωμής (έτη)'),
        ),
    ]
