# Generated by Django 5.1.6 on 2025-09-29 08:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('roofThermalInsulation', '0004_roofthermalinsulation_internal_rate_of_return_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roofthermalinsulation',
            unique_together={('building', 'created_by')},
        ),
    ]
