# Generated by Django 5.1.6 on 2025-05-18 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolingSystem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heat_pump_type', models.CharField(max_length=255, verbose_name='Heat Pump Type')),
                ('power_kw', models.FloatField(verbose_name='Power (kW)')),
                ('construction_year', models.IntegerField(verbose_name='Year of Construction')),
                ('energy_efficiency_ratio', models.FloatField(verbose_name='Energy Efficiency Ratio (EER)')),
                ('maintenance_period', models.CharField(max_length=255, verbose_name='Maintenance Period')),
                ('operating_hours', models.CharField(max_length=255, verbose_name='Operating Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooling_systems', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooling_systems', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooling_systems', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
        ),
    ]
