# Generated by Django 5.1.6 on 2025-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolingsystem',
            name='cooling_system_type',
            field=models.CharField(blank=True, choices=[('central_air', 'Κεντρικό Κλιματισμού'), ('split_unit', 'Split Unit'), ('window_unit', 'Μονάδα Παραθύρου'), ('portable', 'Φορητό'), ('evaporative', 'Εξατμιστικό'), ('heat_pump', 'Αντλία Θερμότητας'), ('chiller', 'Ψύκτης'), ('other', 'Άλλο')], max_length=50, null=True, verbose_name='Τύπος Συστήματος Ψύξης'),
        ),
        migrations.AddField(
            model_name='coolingsystem',
            name='cooling_unit_accessibility',
            field=models.CharField(blank=True, choices=[('easy', 'Εύκολη Πρόσβαση'), ('moderate', 'Μέτρια Πρόσβαση'), ('difficult', 'Δύσκολη Πρόσβαση'), ('restricted', 'Περιορισμένη Πρόσβαση')], max_length=50, null=True, verbose_name='Δυνατότητα Πρόσβασης στη Μονάδα Ψύξης'),
        ),
    ]
