# Generated by Django 5.1.6 on 2025-06-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingSystem', '0002_coolingsystem_cooling_system_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingsystem',
            name='cooling_system_type',
            field=models.CharField(blank=True, help_text='Εισάγετε τον τύπο του συστήματος ψύξης', max_length=255, null=True, verbose_name='Τύπος Συστήματος Ψύξης'),
        ),
    ]
