# Generated by Django 4.2.3 on 2025-06-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingSystem', '0003_alter_coolingsystem_cooling_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingsystem',
            name='cooling_unit_accessibility',
            field=models.CharField(blank=True, help_text='Εισάγετε τη δυνατότητα πρόσβασης στη μονάδα ψύξης', max_length=255, null=True, verbose_name='Δυνατότητα Πρόσβασης στη Μονάδα Ψύξης'),
        ),
    ]
