# Generated by Django 5.1.6 on 2025-06-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingSystem', '0004_alter_coolingsystem_cooling_unit_accessibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingsystem',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Construction'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='energy_efficiency_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy Efficiency Ratio (EER)'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='heat_pump_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Heat Pump Type'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='maintenance_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maintenance Period'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating Hours'),
        ),
        migrations.AlterField(
            model_name='coolingsystem',
            name='power_kw',
            field=models.FloatField(blank=True, null=True, verbose_name='Power (kW)'),
        ),
    ]
