# Generated by Django 5.1.6 on 2025-09-30 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('coolingSystem', '0005_alter_coolingsystem_construction_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coolingsystem',
            options={'verbose_name': 'Σύστημα Ψύξης', 'verbose_name_plural': 'Συστήματα Ψύξης'},
        ),
        migrations.AlterUniqueTogether(
            name='coolingsystem',
            unique_together={('building', 'user')},
        ),
    ]
