# Generated by Django 5.1.6 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolingSystem', '0006_alter_coolingsystem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolingsystem',
            name='power_kw',
            field=models.FloatField(blank=True, null=True, verbose_name='Power (W)'),
        ),
    ]
