# Generated by Django 5.1.6 on 2025-09-30 07:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('domesticHotWaterSystem', '0002_domestichotwatersystem_heating_system_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domestichotwatersystem',
            options={'verbose_name': 'Σύστημα Ζεστού Νερού Χρήσης', 'verbose_name_plural': 'Συστήματα Ζεστού Νερού Χρήσης'},
        ),
        migrations.AlterUniqueTogether(
            name='domestichotwatersystem',
            unique_together={('building', 'user')},
        ),
    ]
