# Generated by Django 5.1.6 on 2025-07-11 20:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotovoltaicSystem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pv_panels_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Φωτοβολταϊκών Πλαισίων')),
                ('pv_panels_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Φωτοβολταϊκών Πλαισίων (€)')),
                ('pv_panels_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Φωτοβολταϊκών Πλαισίων (€)')),
                ('metal_bases_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Μεταλλικών Βάσεων Στήριξης')),
                ('metal_bases_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Μεταλλικών Βάσεων Στήριξης (€)')),
                ('metal_bases_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Μεταλλικών Βάσεων Στήριξης (€)')),
                ('piping_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Σωληνώσεων')),
                ('piping_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Σωληνώσεων (€)')),
                ('piping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Σωληνώσεων (€)')),
                ('wiring_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Καλωδιώσεων')),
                ('wiring_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Καλωδιώσεων (€)')),
                ('wiring_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Καλωδιώσεων (€)')),
                ('inverter_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Μετατροπέων Ισχύος')),
                ('inverter_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Μετατροπέων Ισχύος (€)')),
                ('inverter_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Μετατροπέων Ισχύος (€)')),
                ('installation_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ποσότητα Εγκατάστασης')),
                ('installation_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Τιμή Μονάδας Εγκατάστασης (€)')),
                ('installation_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Δαπάνη Εγκατάστασης (€)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Εκτιμώμενο κόστος (€)')),
                ('unexpected_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Απρόβλεπτες δαπάνες 9% (€)')),
                ('value_after_unexpected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Αξία μετά τις απρόβλεπτες δαπάνες (€)')),
                ('tax_burden', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Επιβάρυνση φόρου 24% (€)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Συνολικό κόστος (€)')),
                ('power_per_panel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ισχύς ανά πλαίσιο (W)')),
                ('collector_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Βαθμός απόδοσης συλλεκτών (%)')),
                ('installation_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Κλίση τοποθέτησης (°)')),
                ('pv_usage', models.CharField(blank=True, help_text='π.χ. Για ίδια κατανάλωση', max_length=255, null=True, verbose_name='Χρήση Φ/Β')),
                ('pv_system_type', models.CharField(blank=True, help_text='π.χ. Μονοκρυσταλλικό', max_length=255, null=True, verbose_name='Τύπος Φ/Β συστήματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photovoltaic_systems', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photovoltaic_systems', to='project.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photovoltaic_systems', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Εγκατάσταση Φωτοβολταϊκών',
                'verbose_name_plural': 'Εγκαταστάσεις Φωτοβολταϊκών',
            },
        ),
    ]
