# Generated by Django 5.1.6 on 2025-07-13 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εκτιμώμενο κόστος (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='installation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Εγκατάστασης (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='installation_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Εγκατάστασης'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='installation_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Εγκατάστασης (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='inverter_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Μετατροπέων Ισχύος (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='inverter_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Μετατροπέων Ισχύος'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='inverter_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Μετατροπέων Ισχύος (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='metal_bases_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Μεταλλικών Βάσεων Στήριξης (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='metal_bases_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Μεταλλικών Βάσεων Στήριξης'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='metal_bases_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Μεταλλικών Βάσεων Στήριξης (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='piping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Σωληνώσεων (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='piping_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Σωληνώσεων'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='piping_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Σωληνώσεων (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='pv_panels_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Φωτοβολταϊκών Πλαισίων (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='pv_panels_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Φωτοβολταϊκών Πλαισίων'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='pv_panels_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Φωτοβολταϊκών Πλαισίων (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='tax_burden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Επιβάρυνση φόρου 24% (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Συνολικό κόστος (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='unexpected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Απρόβλεπτες δαπάνες 9% (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='value_after_unexpected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Αξία μετά τις απρόβλεπτες δαπάνες (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='wiring_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Δαπάνη Καλωδιώσεων (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='wiring_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσότητα Καλωδιώσεων'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='wiring_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τιμή Μονάδας Καλωδιώσεων (€)'),
        ),
    ]
