# Generated by Django 5.1.6 on 2025-07-13 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0002_alter_photovoltaicsystem_estimated_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='annual_energy_production',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσια παραγωγή ενέργειας (kWh)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='annual_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσια εξοικονόμηση (€)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='carbon_footprint_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μείωση αποτυπώματος άνθρακα (kg CO2/έτος)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='investment_return',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Απόδοση επένδυσης (%)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='net_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Καθαρό κόστος (€)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='payback_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Περίοδος απόσβεσης (έτη)'),
        ),
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='subsidy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό επιδότησης (€)'),
        ),
    ]
