# Generated by Django 5.1.6 on 2025-08-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0003_photovoltaicsystem_annual_energy_production_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='net_present_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός NPV με προεξοφλητικό συντελεστή', max_digits=12, null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)'),
        ),
    ]
