# Generated by Django 4.2.3 on 2025-11-17 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0006_photovoltaicsystem_annual_operational_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='annual_operational_costs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ετήσια κόστη συντήρησης και λειτουργίας', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσια λειτουργικά κόστη (€)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Επιτόκιο προεξόφλησης για τον υπολογισμό NPV', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Επιτόκιο προεξόφλησης (%)'),
        ),
    ]
