# Generated by Django 4.2.3 on 2025-11-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0007_alter_photovoltaicsystem_annual_operational_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photovoltaicsystem',
            name='internal_rate_of_return',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός IRR με Newton-Raphson', max_digits=8, null=True, verbose_name='Εσωτερικός βαθμός απόδοσης - IRR (%)'),
        ),
    ]
