# Generated by Django 4.2.3 on 2025-11-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0008_photovoltaicsystem_internal_rate_of_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photovoltaicsystem',
            name='investment_return',
        ),
    ]
