# Generated by Django 4.2.3 on 2025-11-28 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0009_remove_photovoltaicsystem_investment_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='collector_efficiency',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Υποχρεωτικό πεδίο για τον υπολογισμό της ετήσιας παραγωγής', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Βαθμός απόδοσης συλλεκτών (%)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Επιτόκιο αναγωγής για τον υπολογισμό NPV', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='installation_angle',
            field=models.DecimalField(decimal_places=2, default=32.0, help_text='Υποχρεωτικό πεδίο για τον υπολογισμό της ετήσιας παραγωγής', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='Κλίση τοποθέτησης (°)'),
        ),
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='power_per_panel',
            field=models.DecimalField(decimal_places=2, default=400.0, help_text='Υποχρεωτικό πεδίο για τον υπολογισμό της ετήσιας παραγωγής', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ισχύς ανά πλαίσιο (W)'),
        ),
    ]
