# Generated by Django 5.1.6 on 2026-04-27 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photovoltaicSystem', '0011_photovoltaicsystem_discounted_payback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photovoltaicsystem',
            name='discounted_payback_period',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Προεξοφλημένη περίοδος απόσβεσης (έτη)'),
        ),
    ]
