# Generated by Django 5.1.6 on 2025-08-01 06:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExteriorBlinds',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('window_area', models.FloatField(help_text='Συνολική επιφάνεια παραθύρων σε τετραγωνικά μέτρα', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Επιφάνεια παραθύρων (m²)')),
                ('cost_per_m2', models.FloatField(help_text='Κόστος εγκατάστασης περσίδων ανά τετραγωνικό μέτρο', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ανά m² (€)')),
                ('installation_cost', models.FloatField(default=0, help_text='Επιπλέον κόστος εγκατάστασης', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος εγκατάστασης (€)')),
                ('maintenance_cost', models.FloatField(default=0, help_text='Ετήσιο κόστος συντήρησης των περσίδων', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσιο κόστος συντήρησης (€)')),
                ('cooling_energy_savings', models.FloatField(help_text='Ετήσια εξοικονόμηση ενέργειας λόγω μείωσης φόρτου ψύξης', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση ενέργειας ψύξης (kWh/έτος)')),
                ('energy_cost_kwh', models.FloatField(default=0.15, help_text='Κόστος ενέργειας σε ευρώ ανά kWh', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ενέργειας (€/kWh)')),
                ('time_period', models.IntegerField(default=20, help_text='Χρονικό διάστημα αξιολόγησης της επένδυσης', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Χρονικό διάστημα (έτη)')),
                ('discount_rate', models.FloatField(default=5.0, help_text='Προεξοφλητικός συντελεστής για τον υπολογισμό NPV', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Προεξοφλητικός συντελεστής (%)')),
                ('total_investment_cost', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός συνολικού κόστους', null=True, verbose_name='Συνολικό κόστος επένδυσης (€)')),
                ('annual_energy_savings', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός ετήσιας εξοικονόμησης', null=True, verbose_name='Ετήσια ενεργειακή εξοικονόμηση (€)')),
                ('annual_economic_benefit', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός ετήσιου οφέλους', null=True, verbose_name='Ετήσιο οικονομικό όφελος (€)')),
                ('payback_period', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός περιόδου αποπληρωμής', null=True, verbose_name='Περίοδος αποπληρωμής (έτη)')),
                ('net_present_value', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός NPV', null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)')),
                ('internal_rate_of_return', models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός IRR', null=True, verbose_name='Εσωτερικός βαθμός απόδοσης - IRR (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_blinds', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior_blinds', to='project.project')),
            ],
            options={
                'verbose_name': 'Εγκατάσταση Εξωτερικών Περσίδων',
                'verbose_name_plural': 'Εγκαταστάσεις Εξωτερικών Περσίδων',
                'unique_together': {('building', 'project')},
            },
        ),
    ]
