# Generated by Django 4.2.3 on 2025-11-20 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteriorBlinds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exteriorblinds',
            name='cooling_months',
            field=models.IntegerField(default=5, help_text='Αριθμός μηνών που λειτουργεί το σύστημα ψύξης (συνήθως 4-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Μήνες λειτουργίας ψύξης'),
        ),
        migrations.AddField(
            model_name='exteriorblinds',
            name='cooling_system_eer',
            field=models.FloatField(default=2.5, help_text='Energy Efficiency Ratio του συστήματος ψύξης (συνήθως 2.0-3.5)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Απόδοση συστήματος ψύξης (EER)'),
        ),
        migrations.AddField(
            model_name='exteriorblinds',
            name='shading_coefficient',
            field=models.FloatField(default=70.0, help_text='Ποσοστό μείωσης ηλιακών κερδών από τις περσίδες (συνήθως 60-80%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Συντελεστής σκίασης περσίδων (%)'),
        ),
        migrations.AddField(
            model_name='exteriorblinds',
            name='solar_radiation',
            field=models.FloatField(default=5.0, help_text='Μέση ημερήσια ηλιακή ακτινοβολία για τους μήνες ψύξης', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μέση ημερήσια ηλιακή ακτινοβολία (kWh/m²/ημέρα)'),
        ),
        migrations.AlterField(
            model_name='exteriorblinds',
            name='cooling_energy_savings',
            field=models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός ετήσιας εξοικονόμησης ενέργειας ψύξης', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση ενέργειας ψύξης (kWh/έτος)'),
        ),
    ]
