# Generated by Django 4.2.3 on 2025-11-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteriorBlinds', '0002_exteriorblinds_cooling_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteriorblinds',
            name='cooling_energy_savings',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Αυτόματος υπολογισμός ετήσιας εξοικονόμησης ενέργειας ψύξης', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση ενέργειας ψύξης (kWh/έτος)'),
        ),
    ]
