# Generated by Django 4.2.3 on 2025-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteriorBlinds', '0003_alter_exteriorblinds_cooling_energy_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteriorblinds',
            name='net_present_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός NPV', max_digits=12, null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)'),
        ),
    ]
