# Generated by Django 5.1.6 on 2026-04-27 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exteriorBlinds', '0005_exteriorblinds_discounted_payback_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteriorblinds',
            name='discount_rate',
            field=models.FloatField(default=5.0, help_text='Επιτόκιο αναγωγής για τον υπολογισμό NPV', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
    ]
