# Generated by Django 5.1.6 on 2025-06-23 09:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0003_alter_building_energy_zone_alter_building_prefecture'),
        ('materials', '0001_initial'),
        ('project', '0002_project_buildings_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalWallThermalInsulation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('u_coefficient', models.FloatField(blank=True, help_text='Υπολογίζεται αυτόματα: U = 1/R_total', null=True, verbose_name='Συντελεστής U (W/m²K)')),
                ('winter_hourly_losses', models.FloatField(blank=True, null=True, verbose_name='Ωριαίες απώλειες χειμερινών μηνών (kW)')),
                ('summer_hourly_losses', models.FloatField(blank=True, null=True, verbose_name='Ωριαίες απώλειες θερινών μηνών (kW)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building', verbose_name='Κτίριο')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Έργο')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Θερμομόνωση Εξωτερικής Τοιχοποιίας',
                'verbose_name_plural': 'Θερμομονώσεις Εξωτερικής Τοιχοποιίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThermalInsulationMaterialLayer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface_type', models.CharField(choices=[('internal', 'Εσωτερική'), ('external', 'Εξωτερική'), ('intermediate', 'Ενδιάμεση')], max_length=20, verbose_name='Τύπος επιφάνειας')),
                ('thickness', models.FloatField(help_text='Πάχος του υλικού σε μέτρα', verbose_name='Πάχος (m)')),
                ('surface_area', models.FloatField(help_text='Επιφάνεια του υλικού σε τετραγωνικά μέτρα', verbose_name='Επιφάνεια (m²)')),
                ('cost', models.FloatField(help_text='Κόστος του υλικού σε ευρώ', verbose_name='Κόστος (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Υλικό')),
                ('thermal_insulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_layers', to='thermalInsulation.externalwallthermalinsulation', verbose_name='Θερμομόνωση')),
            ],
            options={
                'verbose_name': 'Στρώση Υλικού Θερμομόνωσης',
                'verbose_name_plural': 'Στρώσεις Υλικών Θερμομόνωσης',
                'ordering': ['thermal_insulation', 'created_at'],
            },
        ),
    ]
