# Generated by Django 5.1.6 on 2025-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermalInsulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='annual_benefit',
            field=models.FloatField(blank=True, help_text='Ετήσιο όφελος από εξοικονόμηση ενέργειας', null=True, verbose_name='Ετήσιο όφελος (€)'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='annual_operating_costs',
            field=models.FloatField(blank=True, help_text='Ετήσια λειτουργικά και συντήρησης έξοδα', null=True, verbose_name='Λειτουργικά έξοδα ανά έτος (€)'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='cooling_hours_per_year',
            field=models.FloatField(blank=True, help_text='Ώρες λειτουργίας ψύξης ανά έτος', null=True, verbose_name='Ώρες ψύξης ανά έτος'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='discount_rate',
            field=models.FloatField(blank=True, help_text='Επιτόκιο αναγωγής για υπολογισμό NPV', null=True, verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='heating_hours_per_year',
            field=models.FloatField(blank=True, help_text='Ώρες λειτουργίας θέρμανσης ανά έτος', null=True, verbose_name='Ώρες θέρμανσης ανά έτος'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='net_present_value',
            field=models.FloatField(blank=True, help_text='Καθαρή παρούσα αξία της επένδυσης', null=True, verbose_name='Καθαρή παρούσα αξία (€)'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='time_period_years',
            field=models.IntegerField(blank=True, help_text='Περίοδος αξιολόγησης της επένδυσης σε έτη', null=True, verbose_name='Χρονικό διάστημα (έτη)'),
        ),
        migrations.AddField(
            model_name='externalwallthermalinsulation',
            name='total_cost',
            field=models.FloatField(blank=True, help_text='Συνολικό κόστος υλικών και εργασίας', null=True, verbose_name='Συνολικό κόστος (€)'),
        ),
        migrations.AddField(
            model_name='thermalinsulationmateriallayer',
            name='material_type',
            field=models.CharField(choices=[('old', 'Παλιά Υλικά'), ('new', 'Νέα Υλικά')], default='new', help_text='Διάκριση μεταξύ παλιών και νέων υλικών', max_length=10, verbose_name='Τύπος Υλικού'),
        ),
        migrations.AlterField(
            model_name='thermalinsulationmateriallayer',
            name='surface_type',
            field=models.CharField(choices=[('external_walls_outdoor', 'Εξωτερικοί τοίχοι σε επαφή με τον εξωτερικό αέρα'), ('internal', 'Εσωτερική'), ('external', 'Εξωτερική'), ('intermediate', 'Ενδιάμεση')], default='external_walls_outdoor', max_length=30, verbose_name='Τύπος επιφάνειας'),
        ),
    ]
