# Generated by Django 5.1.6 on 2025-08-01 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0007_alter_building_prefecture'),
        ('project', '0002_project_buildings_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticLightingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_area', models.FloatField(help_text='Συνολική επιφάνεια που καλύπτει το σύστημα φωτισμού', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Επιφάνεια φωτισμού (m²)')),
                ('cost_per_m2', models.DecimalField(decimal_places=2, help_text='Κόστος εγκατάστασης συστήματος αυτόματου ελέγχου ανά τετραγωνικό μέτρο', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ανά m² (€)')),
                ('installation_cost', models.DecimalField(decimal_places=2, default=0, help_text='Επιπλέον κόστος εγκατάστασης (εργασία, υλικά κλπ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος εγκατάστασης (€)')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, help_text='Ετήσιο κόστος συντήρησης και λειτουργίας του συστήματος', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσιο κόστος συντήρησης (€)')),
                ('lighting_energy_savings', models.FloatField(help_text='Ετήσια εξοικονόμηση ενέργειας από την αυτόματη ρύθμιση φωτισμού', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εξοικονόμηση ενέργειας φωτισμού (kWh/έτος)')),
                ('energy_cost_kwh', models.DecimalField(decimal_places=3, default=0.15, help_text='Τιμή ενέργειας ανά kWh', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ενέργειας (€/kWh)')),
                ('time_period', models.IntegerField(default=20, help_text='Περίοδος αξιολόγησης της επένδυσης σε έτη', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Χρονικό διάστημα (έτη)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Προεξοφλητικός συντελεστής για υπολογισμό NPV', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Προεξοφλητικός συντελεστής (%)')),
                ('total_investment_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός: (Επιφάνεια × Κόστος/m²) + Κόστος εγκατάστασης', max_digits=12, null=True, verbose_name='Συνολικό κόστος επένδυσης (€)')),
                ('annual_energy_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός: Εξοικονόμηση kWh × Κόστος ενέργειας', max_digits=12, null=True, verbose_name='Ετήσια ενεργειακή εξοικονόμηση (€)')),
                ('annual_economic_benefit', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός: Εξοικονόμηση - Κόστος συντήρησης', max_digits=12, null=True, verbose_name='Ετήσιο οικονομικό όφελος (€)')),
                ('payback_period', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός: Κόστος επένδυσης ÷ Ετήσιο όφελος', max_digits=8, null=True, verbose_name='Περίοδος αποπληρωμής (έτη)')),
                ('net_present_value', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός NPV με προεξοφλητικό συντελεστή', max_digits=12, null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)')),
                ('internal_rate_of_return', models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός IRR (απλοποιημένος)', max_digits=8, null=True, verbose_name='Εσωτερικός βαθμός απόδοσης - IRR (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_lighting_control', to='building.building')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_lighting_controls', to='project.project')),
            ],
            options={
                'verbose_name': 'Αυτόματος Έλεγχος Φωτισμού',
                'verbose_name_plural': 'Αυτόματος Έλεγχος Φωτισμού',
                'db_table': 'automatic_lighting_control',
            },
        ),
    ]
