# Generated by Django 4.2.3 on 2025-11-20 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('automaticLightingControl', '0003_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
