# Generated by Django 4.2.3 on 2025-11-20 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticLightingControl', '0005_remove_automaticlightingcontrol_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticlightingcontrol',
            name='current_lighting_power_density',
            field=models.FloatField(default=10, help_text='Μέση ισχύς φωτισμού ανά τετραγωνικό μέτρο πριν την εγκατάσταση', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Τρέχουσα ισχύς φωτισμού (W/m²)'),
        ),
        migrations.AddField(
            model_name='automaticlightingcontrol',
            name='estimated_savings_percentage',
            field=models.FloatField(default=30, help_text='Ποσοστό εξοικονόμησης ενέργειας από αυτόματο έλεγχο (συνήθως 25-40%)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Εκτιμώμενο ποσοστό εξοικονόμησης (%)'),
        ),
        migrations.AddField(
            model_name='automaticlightingcontrol',
            name='operating_days_per_year',
            field=models.IntegerField(default=250, help_text='Αριθμός ημερών που λειτουργεί το κτίριο ετησίως', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ημέρες λειτουργίας ανά έτος'),
        ),
        migrations.AddField(
            model_name='automaticlightingcontrol',
            name='operating_hours_per_day',
            field=models.FloatField(default=8, help_text='Μέσες ώρες που λειτουργεί ο φωτισμός ημερησίως', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Ώρες λειτουργίας φωτισμού ανά ημέρα'),
        ),
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='lighting_energy_savings',
            field=models.FloatField(blank=True, help_text='Αυτόματος υπολογισμός: Τρέχουσα κατανάλωση × Ποσοστό εξοικονόμησης', null=True, verbose_name='Εξοικονόμηση ενέργειας φωτισμού (kWh/έτος)'),
        ),
    ]
