# Generated by Django 4.2.3 on 2025-11-21 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticLightingControl', '0006_automaticlightingcontrol_current_lighting_power_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='energy_cost_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Αυτόματη λήψη από το έργο - Τιμή ενέργειας ανά kWh', max_digits=6, null=True, verbose_name='Κόστος ενέργειας (€/kWh)'),
        ),
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='installation_cost',
            field=models.DecimalField(decimal_places=2, help_text='Επιπλέον κόστος εγκατάστασης (εργασία, υλικά κλπ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος εγκατάστασης (€)'),
        ),
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, help_text='Ετήσιο κόστος συντήρησης και λειτουργίας του συστήματος', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ετήσιο κόστος συντήρησης (€)'),
        ),
    ]
