# Generated by Django 4.2.3 on 2025-11-21 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automaticLightingControl', '0007_alter_automaticlightingcontrol_energy_cost_kwh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Επιτόκιο αναγωγής για υπολογισμό NPV', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Επιτόκιο αναγωγής (%)'),
        ),
        migrations.AlterField(
            model_name='automaticlightingcontrol',
            name='net_present_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Αυτόματος υπολογισμός NPV με επιτόκιο αναγωγής', max_digits=12, null=True, verbose_name='Καθαρή παρούσα αξία - NPV (€)'),
        ),
    ]
